import React from 'react';


const Card = ({ card, onClick, isSelected, hidden }) => {
    const { suit, value } = card;

    // Configuration
    const originalSprite = '/assets/cartas/sprite_corregido.png';
    const extrasSprite = '/assets/cartas/sprite_extras.png';

    const suitOrder = ['oros', 'bastos', 'espadas', 'copas'];
    const standardValues = [1, 2, 3, 4, 5, 6, 7, 10, 11, 12];

    let spritePath = originalSprite;
    let rIdx = 0;
    let cIdx = 0;
    let numCards = 10;
    let numRows = 4;

    if (standardValues.includes(value) && suit !== 'joker') {
        // Use standard 40-card sprite (10x4)
        spritePath = originalSprite;
        rIdx = suitOrder.indexOf(suit);
        cIdx = standardValues.indexOf(value);
        numCards = 10;
        numRows = 4;
    } else {
        // Use extras sprite (5x3 grid generated by AI)
        // Row 0: 8s (Good)
        // Row 1: 9s (Bad - Skip)
        // Row 2: 9s (Good)
        spritePath = extrasSprite;
        numCards = 5;
        numRows = 3;

        if (suit === 'joker') {
            rIdx = value === 1 ? 0 : 2;
            cIdx = 4;
        } else {
            rIdx = value === 8 ? 0 : 2;
            cIdx = suitOrder.indexOf(suit);
        }
    }

    // Geometry
    const imgWidth = numCards * 100;
    const imgHeight = numRows * 100;

    const leftPos = -(cIdx * 100);
    const topPos = -(rIdx * 100);

    const backStyle = {
        backgroundColor: '#1e3a8a',
        backgroundImage: `
          repeating-linear-gradient(45deg, transparent, transparent 9px, rgba(255,255,255,0.2) 10px, transparent 11px),
          repeating-linear-gradient(-45deg, transparent, transparent 9px, rgba(255,255,255,0.2) 10px, transparent 11px)
      `,
    };

    return (
        <div
            onClick={() => onClick && onClick(card)}
            className={`relative w-24 h-36 rounded-xl shadow-xl ${isSelected ? 'ring-4 ring-yellow-400 scale-105 z-10' : 'hover:shadow-2xl'
                } bg-white overflow-hidden border-2 border-white/10 select-none group pointer-events-auto transition-all duration-300 ease-out active:scale-95`}
        >
            {/* Hidden internal label */}
            <div className="sr-only">{value} of {suit}</div>

            {/* Card Face */}
            {!hidden && (
                <div className="absolute inset-0 overflow-hidden rounded-lg bg-white">
                    <img
                        src={spritePath}
                        alt=""
                        className="max-w-none absolute select-none pointer-events-none"
                        style={{
                            width: `${imgWidth}%`,
                            height: `${imgHeight}%`,
                            left: `${leftPos}%`,
                            top: `${topPos}%`,
                            imageRendering: 'auto'
                        }}
                    />
                </div>
            )}

            {/* Back Decoration */}
            {hidden && (
                <div className="w-full h-full relative" style={backStyle}>
                    <div className="absolute inset-2 border-2 border-white/20 rounded-md"></div>
                    <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-8 h-8 border-2 border-white/40 rotate-45 bg-white/10 shadow-sm"></div>
                </div>
            )}
        </div>
    );
};

export default Card;
